question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "Which of the following men does not have a chemical element named after him?",
     "correct_answer": "Sir Isaac Newton",
     "incorrect_answers": ["Albert Einstein", "Niels Bohr", "Enrico Fermi"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science: Computers",
     "question": "Who invented the &quot;Spanning Tree Protocol&quot;?",
     "correct_answer": "Radia Perlman",
     "incorrect_answers": ["Paul Vixie", "Vint Cerf", "Michael Roberts"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Who played the Cenobite called &quot;Pinhead&quot; in the original Hellraiser films?",
     "correct_answer": "Doug Bradley",
     "incorrect_answers": ["Doug Jones", "Doug Savant", "Doug Benson"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "The music group Daft Punk got their name from a negative review they recieved.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Which of the following characters is NOT a female marriage candidate in the game Stardew Valley?",
     "correct_answer": "Caroline", "incorrect_answers": ["Abigail", "Haley", "Leah"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
     "correct_answer": "C#", "incorrect_answers": ["Java", "C++", "Objective-C"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The main protagonist of the fifth part of JoJo&#039;s Bizarre Adventure is which of the following?",
     "correct_answer": "Giorno Giovanna",
     "incorrect_answers": ["Guido Mista", "Jonathan Joestar", "Joey JoJo"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What is the longest river in Europe?", "correct_answer": "Volga",
     "incorrect_answers": ["Danube", "Rhine", "Thames"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Television",
     "question": "What NBC sitcom once saw two of its characters try to pitch NBC on a sitcom about nothing?",
     "correct_answer": "Seinfeld",
     "incorrect_answers": ["Frasier", "Becker", "Friends"]},
    {"type": "multiple", "difficulty": "medium", "category": "Animals",
     "question": "Which of these species is not extinct?",
     "correct_answer": "Komodo dragon",
     "incorrect_answers": ["Japanese sea lion", "Tasmanian tiger", "Saudi gazelle"]},
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "What name was historically used for the Turkish city currently known as Istanbul?",
     "correct_answer": "Constantinople",
     "incorrect_answers": ["H&uuml;davendigar", "S&ouml;\u011f&uuml;t", "Adrianople"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "When was the first mammal successfully cloned?",
     "correct_answer": "1996", "incorrect_answers": ["2009", "1999", "1985"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Pink Floyd made this song for their previous lead singer Syd Barrett.",
     "correct_answer": "Shine On You Crazy Diamond",
     "incorrect_answers": ["Wish You Were Here", "Have A Cigar",
                           "Welcome to the Machine"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Dota 2, Wraith King was previously known as...",
     "correct_answer": "Skeleton King",
     "incorrect_answers": ["Reaper King", "Skull King", "Hell King"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "What is Hypernatremia?",
     "correct_answer": "Increase in blood sodium",
     "incorrect_answers": ["Decrease in blood potassium", "Increase in blood glucose",
                           "Decrease in blood iron"]},
    {"type": "multiple", "difficulty": "medium", "category": "Art",
     "question": "Which time signature is commonly known as &ldquo;Cut Time?&rdquo;",
     "correct_answer": "2\/2", "incorrect_answers": ["4\/4", "6\/8", "3\/4"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Who had hits in the 70s with the songs &quot;Lonely Boy&quot; and &quot;Never Let Her Slip Away&quot;?",
     "correct_answer": "Andrew Gold",
     "incorrect_answers": ["Elton John", "Leo Sayer", "Barry White "]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Musicals &amp; Theatres",
     "question": "Who played &quot;Charlie Price&quot; in the musical &quot;Kinky Boots&quot; on Broadway in New York from May 26th - Aug 6th 2017?",
     "correct_answer": "Brendon Urie",
     "incorrect_answers": ["Ed Sheeren", "Tom Cruise", "Dallon Weekes"]},
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "During WWII, in 1945, the United States dropped atomic bombs on the two Japanese cities of Hiroshima and what other city?",
     "correct_answer": "Nagasaki",
     "incorrect_answers": ["Kawasaki", "Tokyo", "Kagoshima"]},
    {"type": "multiple", "difficulty": "easy", "category": "Sports",
     "question": "Who did Steven Gerrard win the Champions League with?",
     "correct_answer": "Liverpool",
     "incorrect_answers": ["Real Madrid", "Chelsea", "Man City"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "Directly between the Washington Monument and the Reflecting Pool is a memorial to which war?",
     "correct_answer": "World War II",
     "incorrect_answers": ["Vietnam War", "American Civil War",
                           "American Revolutionary War"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Musicals &amp; Theatres",
     "question": "IMAX stands for Image Maximum.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "multiple", "difficulty": "hard",
                                       "category": "Entertainment: Video Games",
                                       "question": "In the Gamecube Version of &quot;Resident Evil&quot; what text document is open on the monitor of the computer in the Visual Data Room?",
                                       "correct_answer": "A GDC Document",
                                       "incorrect_answers": ["Text Document on Herbs",
                                                             "Nothing",
                                                             "Document on B.O.Ws"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "Which of these is NOT a city in Saudi Arabia?",
     "correct_answer": "Dubai", "incorrect_answers": ["Riyadh", "Mecca", "Medina"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Books",
     "question": "What is the fourth book of the Old Testament?",
     "correct_answer": "Numbers",
     "incorrect_answers": ["Genesis", "Exodus", "Leviticus"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "&quot;Lift Your Spirit&quot; is an album by which artist?",
     "correct_answer": "Aloe Blacc",
     "incorrect_answers": ["Lena Meyer-Landrut", "Stevie Wonder", "Taylor Swift"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What is the capital of Seychelles?", "correct_answer": "Victoria",
     "incorrect_answers": ["Luanda", "N&#039;Djamena", "Tripoli"]},
    {"type": "multiple", "difficulty": "hard", "category": "Geography",
     "question": "What is the most common climbing route for the second highest mountain in the world, K2?",
     "correct_answer": "Abruzzi Spur",
     "incorrect_answers": ["Magic Line", "Cesen Route", "Polish Line"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Musicals &amp; Theatres",
     "question": "After England, more Shakespeare plays are set in this present day country than in any other.",
     "correct_answer": "Italy",
     "incorrect_answers": ["United States", "Greece", "France"]},
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "Which country is the home of the largest Japanese population outside of Japan?",
     "correct_answer": "Brazil",
     "incorrect_answers": ["China", "Russia", "The United States"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In the ARPG &quot;Path of Exile,&quot; what is the highest amount of sockets that an item can have?",
     "correct_answer": "6", "incorrect_answers": ["5", "4", "8"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "Deionized water is water with which of the following removed?",
     "correct_answer": "Iron",
     "incorrect_answers": ["Oxygen", "Hydrogen", "Uncharged atoms"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "What year was Red Hot Chill Pepper&#039;s album &quot;Californication&quot; released?",
     "correct_answer": "1999", "incorrect_answers": ["1997", "2000", "1992"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "What is the British term for a 64th note?",
     "correct_answer": "Hemidemisemiquaver",
     "incorrect_answers": ["Semihemidemisemiquaver", "Semiquaver", "Demisemiquaver"]},
    {"type": "multiple", "difficulty": "hard", "category": "History",
     "question": "After the 1516 Battle of Marj Dabiq, the Ottoman Empire took control of Jerusalem from which sultanate?",
     "correct_answer": "Mamluk",
     "incorrect_answers": ["Ayyubid", "Ummayyad", "Seljuq"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "What is the name of the world that the MMO &quot;RuneScape&quot; takes place in?",
     "correct_answer": "Gielinor",
     "incorrect_answers": ["Glindor", "Azeroth", "Zaros"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "Who co-founded the YouTube Let&#039;s Play channel &quot;Game Grumps&quot; alongside Newgrounds animator Egoraptor?",
     "correct_answer": "JonTron",
     "incorrect_answers": ["Pewdiepie", "Tobuscus", "Markiplier"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Kanye West&#039;s &quot;Gold Digger&quot; featured which Oscar-winning actor?",
     "correct_answer": "Jamie Foxx",
     "incorrect_answers": ["Alec Baldwin", "Dwayne Johnson", " Bruce Willis"]},
    {"type": "multiple", "difficulty": "easy", "category": "Animals",
     "question": "What is Grumpy Cat&#039;s real name?",
     "correct_answer": "Tardar Sauce",
     "incorrect_answers": ["Sauce", "Minnie", "Broccoli"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "You can square root a negative number with an imaginary number &quot;i&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Comics",
     "question": "What year was the first San Diego Comic-Con?",
     "correct_answer": "1970", "incorrect_answers": ["2000", "1990", "1985"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In Terraria, which of these items is NOT crafted at a Mythril Anvil?",
     "correct_answer": "Ankh Charm",
     "incorrect_answers": ["Venom Staff", "Sky Fracture", "Orichalcum Tools"]},
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "Which famous military commander marched an army, which included war elephants, over the Alps during the Second Punic War?",
     "correct_answer": "Hannibal",
     "incorrect_answers": ["Garmanicus", "Alexander the Great", "Tiberius"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Which of the following is not a faction in Tom Clancy&#039;s The Division?",
     "correct_answer": "CDC",
     "incorrect_answers": ["Cleaners", "Last Man Batallion", "Rikers"]}]
